project:
  type: website
  output-dir: docs

website:
  title: "Jianyuan(Andy) Hu"
  page-footer: 
    left: Created by Jianyuan(Andy) Hu, 2024 
    right: |
     This book was built with <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/jy-andy-hu/AllAboutMe
  repo-branch: main
  repo-actions: issue

  sidebar:
    style: "floating"
    search: true
    background: "none"
    tools:
    - icon: linkedin
      href: http://linkedin.com/in/andyhu1
    - icon: github
      href: https://github.com/jy-andy-hu
    contents:
      - text: "About Me"
        href: index.qmd
      - text: "Project Gallery"
        href: project_gallery.qmd
      - section: "For Education"
        contents:
          - text: "Introduction to SQL"
            href: https://jy-andy-hu.github.io/Education_MySQL_Introduction/
          - text: "A Collection of Practical Projects with R"
            href: https://jy-andy-hu.github.io/Education_R/
          - text: "Capstone Accounting Case (CCI)"
            href: accounting_cci.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true